version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=advertisements_board
    volumes:
      - ./data/mongo/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
    depends_on:
      - mongodb

  main:
    build: .
    working_dir: /src
    restart: always
    ports:
      - 80:3001
    environment:
      - PORT=3001
      - DB_USERNAME=root
      - DB_PASSWORD=password123
      - DB_NAME=advertisements_board
      - DB_HOST=mongodb://mongodb:27017
      - COOKIE_SECRET=secret
    depends_on:
      - mongodb
    volumes:
      - ./:/src


volumes:
  data: